import config from "../app/config";

export const getBazarEntryHtml = (
    recipientName: string,
    creatorName: string,
    productName: string,
    price: number,
    quantity: number,
    unit?: string,
    notes?: string
) => {
    const totalCost = price * quantity;
    return `
        <div style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; max-width: 550px; margin: 0 auto; padding: 25px; border: 1px solid #e2e8f0; border-radius: 12px; background: #ffffff; box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.05), 0 2px 4px -1px rgba(0, 0, 0, 0.03);">
            <div style="text-align: center; border-bottom: 2px solid #edf2f7; padding-bottom: 15px; margin-bottom: 20px;">
                <h2 style="color: #2d3748; margin: 0; font-size: 22px; font-weight: 700; letter-spacing: -0.5px;">Bazar Hisab</h2>
                <p style="color: #718096; margin: 5px 0 0 0; font-size: 14px;">New Daily Expense Logged</p>
            </div>
            
            <p style="color: #4a5568; font-size: 16px; line-height: 1.5; margin-top: 0;">Hello <strong>${recipientName}</strong>,</p>
            <p style="color: #4a5568; font-size: 15px; line-height: 1.5;"><strong>${creatorName}</strong> has logged a new daily bazar entry for your group.</p>
            
            <div style="background-color: #f7fafc; border-left: 4px solid #4f46e5; border-radius: 4px; padding: 18px; margin: 20px 0;">
                <h3 style="margin: 0 0 12px 0; color: #4f46e5; font-size: 16px; text-transform: uppercase; letter-spacing: 0.5px;">Expense Details</h3>
                <table style="width: 100%; border-collapse: collapse; font-size: 15px; color: #4a5568;">
                    <tr>
                        <td style="padding: 6px 0; font-weight: 600; width: 120px;">Product:</td>
                        <td style="padding: 6px 0; color: #1a202c;">${productName}</td>
                    </tr>
                    <tr>
                        <td style="padding: 6px 0; font-weight: 600;">Price:</td>
                        <td style="padding: 6px 0; color: #1a202c;">৳${price}</td>
                    </tr>
                    <tr>
                        <td style="padding: 6px 0; font-weight: 600;">Quantity:</td>
                        <td style="padding: 6px 0; color: #1a202c;">${quantity} ${unit || ""}</td>
                    </tr>
                    <tr style="border-top: 1px solid #e2e8f0;">
                        <td style="padding: 10px 0 6px 0; font-weight: 700; color: #2d3748; font-size: 16px;">Total Cost:</td>
                        <td style="padding: 10px 0 6px 0; font-weight: 700; color: #e53e3e; font-size: 17px;">৳${totalCost}</td>
                    </tr>
                    ${
                        notes
                            ? `<tr>
                                <td style="padding: 8px 0 0 0; font-weight: 600; vertical-align: top;">Notes:</td>
                                <td style="padding: 8px 0 0 0; color: #718096; font-style: italic; font-size: 14px;">${notes}</td>
                               </tr>`
                            : ""
                    }
                </table>
            </div>

            <div style="text-align: center; margin-top: 25px;">
                <a href="${config.client_url || '#'}" style="background: #4f46e5; color: white; padding: 12px 28px; text-decoration: none; border-radius: 6px; font-weight: 600; display: inline-block; box-shadow: 0 4px 6px -1px rgba(79, 70, 229, 0.2);">View Dashboard</a>
            </div>
            
            <p style="color: #a0aec0; font-size: 12px; text-align: center; margin-top: 30px; border-top: 1px solid #edf2f7; padding-top: 15px;">
                This email was auto-generated by Bazar Hisab. Please do not reply directly to this email.
            </p>
        </div>
    `;
};
